export const taskTypeList = {
  stereometria: "Stereometria",
  optymalizacja: "Optymalizacja",
  granice: "Granice",
  trygonometria: "Trygonometria",
  wielomiany: "Wielomiany",
  ciagi: "Ciągi",
  dalgebraiczne: "Dowody algebraiczne",
  dgeometryczne: "Dowody geometryczne",
  nierownosci: "Nierówności",
  rzparametrem: "Równania z parametrem",
  prawdopodobienstwo: "Prawdopodobieństwo",
  kombinatoryka: "Kombinatoryka",
  wbezwzgledne: "Wartości bezwzględne",
  geoanalityczna: "Geometria analityczna",
  planimetria: "Planimetria",
};
